sudo: required

language: generic

services:
  - docker

addons:
  apt:
    packages:
    - shellcheck

before_script:
  - ./bin/build
  - ./bin/start
  - ./bin/migrate

script:
  - ./bin/await
  - ./bin/test
  # Stopping the services isn't part of the test, but we need it to break the build if it fails.
  - ./bin/stop
