version: '3.4'
services:
  consul:
    image: maison:consul
    build: ./services/consul
    restart: always
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './data/services/consul:/consul/data'
    network_mode: host
    environment:
      MAISON_SERVICES_LOCAL_IP: '${MAISON_SERVICES_LOCAL_IP}'
      MAISON_SERVICES_CONSUL_MASTER_ACL_TOKEN: '${MAISON_SERVICES_CONSUL_MASTER_ACL_TOKEN}'
      MAISON_SERVICES_CONSUL_TEMPLATE_ACL_TOKEN: '${MAISON_SERVICES_CONSUL_TEMPLATE_ACL_TOKEN}'
