#!/usr/bin/env bash
# Test Consul.

set -Eeuo pipefail

cd "$(dirname "$0")/.."

set +a
. ./run/.env
set -a

./vendor/wait-for-it "$MAISON_SERVICES_LOCAL_IP:8500"
curl -fsL -o /dev/null "$MAISON_SERVICES_LOCAL_IP:8500"
